[workspace]
members = ["crates/rusterize", "crates/rusterize-cli", "examples/gallery"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/USBashka/Rusterize"

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"

[profile.bench]
lto = "thin"
codegen-units = 1
